##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

## Note: Any command which fails in any stage below result in the command stopping, and endStage being run.
## A flow file can have one or more stages, each with multiple "actions", 
## or your flow file can have multiple stages with fewer actions in each stage.

stages:
  Connect:
    actions: 
      - type: liquibase
        command: connect

  Validation:
    actions: 
      - type: liquibase
        command: validate
        
  Checks-Changelog:
    actions:
      - type: shell
        command: | 
          liquibase checks run --checks-scope=changelog --report-name=checks-report-build-changelog.html --checks-settings-file=checks/liquibase.checks-settings.conf
         
  Status:
    actions:
      - type: liquibase
        command: status
        cmdArgs: {verbose: true, context-filter: DEV}

  Update-SQL:
    actions:
      - type: liquibase
        command: update-sql
        cmdArgs: {context-filter: DEV}
        
  Update:  
    actions:
      - type: liquibase
        command: update
        cmdArgs: {context-filter: DEV}
        globalArgs: { reports-name: "build-report.html" }

## The endStage ALWAYS RUNS. 
## So put actions here which you desire to perform whether previous stages' actions succeed or fail.
## If you do not want any actions to ALWAYS RUN, simply delete the endStage from your flow file.

endStage:
  actions:
    - type: liquibase
      command: history