##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  ENV: ${ENVIRONMENT}
  CLIENT_ID: ${AZURE_CLIENT_ID}
  CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
  TENANT_ID: ${AZURE_TENANT_ID}   
  
stages:
  Snapshot:
    actions:
      - type: liquibase
        command: snapshot
        cmdArgs: 
          {  snapshot-format: json }
        globalArgs: { output-file: 'snapshots/${ENV}-snapshot.json' }
        
      - type: shell
        command: echo 'Snapshot created as snapshots/${ENV}-snapshot.json'

  Upload:
    actions:
      - type: shell
        command: az login --service-principal -u ${CLIENT_ID} -p ${CLIENT_SECRET} -t ${TENANT_ID}