##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  ENV: ${ENVIRONMENT}
  CLIENT_ID: ${AZURE_CREDS_USR}
  CLIENT_SECRET: ${AZURE_CREDS_PSW}
  TENANT_ID: ${AZURE_TENANT_ID}
  SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
  STORAGE_ACCT: ${AZURE_STORAGE_ACCOUNT}  
  
stages:
  Snapshot:
    actions:
      - type: liquibase
        command: snapshot
        cmdArgs: 
          {  snapshot-format: json }
        globalArgs: { output-file: 'snapshots/${ENV}-snapshot.json' }
        
      - type: shell
        command: echo 'Snapshot created as snapshots/${ENV}-snapshot.json'

  AzureUpload:
    actions:
      - type: shell
        command: az login --service-principal -u ${CLIENT_ID} -p ${CLIENT_SECRET} -t ${TENANT_ID}

      - type: shell
        command: az account set --subscription ${SUBSCRIPTION_ID}

      - type: shell
        command: az storage container create --account-name cssnapshots --name jenkins-snapshot --auth-mode login

      - type: shell
        command: az storage blob upload-batch --destination jenkins-snapshot --source ./snapshots --account-name ${STORAGE_ACCT} --overwrite

      - type: shell
        command: az logout
